services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: ./
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
    depends_on:
      - postgres
    entrypoint: ./entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

volumes:
    gems:
    postgres:
    rails_cache: